# Api gateway name
service: employee-bank-details
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employee}
# define a custom variable for dynamodb table name
custom:
  employee: employee-BankDetails-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
  # lambda function name and configuration
functions:
  createEmployee:
    handler: api.BankDeatilsHandler
    name: create-employee-bank-details-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/bankDetails
          method: POST
      - http:
          path: employee/bankDetails/{empId}
          method: PUT
      - http:
          path: employee/salary/{empId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
        Resource: !GetAtt employee.Arn
  
# aws resource that is dynamodb
resources:
  Resources:
    employee:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employee}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1